// ── license.rs — Talus commercial licensing system ────────────────────────
//
// Provides license key validation, feature gating, and online activation.
//
// License key format:
//   base64(JSON payload) . base64(Ed25519 signature)
//
// Payload structure:
//   {
//     "license_id": "TALUS-XXXX-XXXX-XXXX",
//     "tier": "enterprise",
//     "features": ["tui", "web", "auto_kill", "kafka", "clickhouse", "memgraph"],
//     "max_nodes": 0,           // 0 = unlimited
//     "expires_at": "2027-01-01T00:00:00Z",  // null = perpetual
//     "issued_at": "2026-01-01T00:00:00Z",
//     "machine_id": null,       // set after activation
//     "organization": "Acme Corp"
//   }
//
// Activation flow:
//   1. User runs: talus --license activate <KEY>
//   2. Binary generates machine fingerprint (MAC + hostname + CPU)
//   3. Sends { key, machine_id } to activation server
//   4. Server validates key, records activation, returns { token, expires_at }
//   5. Token cached locally in ~/.config/talus/license.json

use std::collections::HashSet;
use std::fs;
use std::io::Write;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use anyhow::{bail, Context, Result};
use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};

// ── Integrity check ───────────────────────────────────────────────────────

/// Compute XOR checksum of a byte slice.
fn xor_checksum(data: &[u8]) -> u8 {
    data.iter().fold(0u8, |acc, &b| acc ^ b)
}

/// XOR checksum of the embedded public key, computed at compile time from
/// `PUBLIC_KEY_BYTES`. Used to detect binary tampering: if someone replaces
/// the public key to accept forged licenses, this checksum will mismatch
/// (assuming they don't also update this constant).
const KEY_CHECKSUM: u8 = {
    let mut acc = 0u8;
    let mut i = 0;
    while i < PUBLIC_KEY_BYTES.len() {
        acc ^= PUBLIC_KEY_BYTES[i];
        i += 1;
    }
    acc
};

// ── Embedded public key for license verification ──────────────────────────

/// Ed25519 public key for verifying license signatures.
/// This key is embedded at compile time and cannot be changed without recompilation.
/// Only the holder of the corresponding private key (the keygen tool) can create valid licenses.
const PUBLIC_KEY_BYTES: [u8; 32] = [
    // Generated by `talus-keygen init` — DO NOT edit manually.
    // This key verifies all license signatures. The corresponding private key
    // is stored OUTSIDE the repository at ~/.secrets/talus/license-keys/
    // (permissions 0600 — never commit it). Key rotated 2026-09-17 after the
    // previous keypair leaked in git history; all pre-rotation licenses are void.
    0x85, 0x0e, 0x6b, 0xbd, 0xc5, 0xb5, 0xd6, 0x6a, 0xe2, 0x49, 0x73, 0xce, 0xf9, 0xe6, 0xe5, 0xba,
    0xf8, 0x87, 0xb2, 0xc7, 0x75, 0xa2, 0xe1, 0x7c, 0xd1, 0xb6, 0xcd, 0x2d, 0x8a, 0xe7, 0x68, 0x45,
];

fn verifying_key() -> &'static VerifyingKey {
    static KEY: OnceLock<VerifyingKey> = OnceLock::new();
    KEY.get_or_init(|| {
        VerifyingKey::from_bytes(&PUBLIC_KEY_BYTES).expect("invalid embedded public key")
    })
}

// ── License data types ────────────────────────────────────────────────────

/// License tier determines feature access.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
pub enum LicenseTier {
    /// Community edition — free, limited features.
    Community,
    /// Enterprise — full feature access.
    Enterprise,
}

impl LicenseTier {
    pub fn display_name(&self) -> &str {
        match self {
            LicenseTier::Community => "Community",
            LicenseTier::Enterprise => "Enterprise",
        }
    }

    /// Default features enabled for this tier.
    pub fn default_features(&self) -> Vec<String> {
        match self {
            LicenseTier::Community => vec!["tui".into(), "plain".into(), "json".into()],
            LicenseTier::Enterprise => vec![
                "tui".into(),
                "plain".into(),
                "json".into(),
                "web".into(),
                "auto_kill".into(),
                "kafka".into(),
                "clickhouse".into(),
                "memgraph".into(),
                "ffi".into(),
            ],
        }
    }
}

impl std::fmt::Display for LicenseTier {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.display_name())
    }
}

/// The signed license payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicensePayload {
    /// Unique license identifier (e.g., "TALUS-A1B2-C3D4-E5F6").
    pub license_id: String,
    /// License tier.
    pub tier: LicenseTier,
    /// Explicit feature allowlist. If present, overrides tier defaults.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<String>>,
    /// Maximum managed nodes (0 = unlimited).
    #[serde(default)]
    pub max_nodes: u32,
    /// Expiration datetime (ISO 8601). None = perpetual.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    /// When the license was issued (ISO 8601).
    pub issued_at: String,
    /// Machine fingerprint set after activation. None = not yet activated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine_id: Option<String>,
    /// Organization name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    /// Seat count for multi-node deployments (1 = single node).
    #[serde(default = "default_seat_count")]
    pub seat_count: u32,
}

fn default_seat_count() -> u32 {
    1
}

impl LicensePayload {
    /// Check if this license is currently valid (not expired).
    pub fn is_expired(&self) -> bool {
        if let Some(ref expires) = self.expires_at {
            if let Ok(expiry) = chrono::NaiveDateTime::parse_from_str(expires, "%Y-%m-%dT%H:%M:%SZ")
            {
                return chrono::Utc::now().naive_utc() > expiry;
            }
        }
        false
    }

    /// Get effective feature set for this license.
    pub fn effective_features(&self) -> HashSet<String> {
        if let Some(ref features) = self.features {
            features.iter().cloned().collect()
        } else {
            self.tier.default_features().iter().cloned().collect()
        }
    }

    /// Check if a specific feature is enabled.
    pub fn has_feature(&self, feature: &str) -> bool {
        self.effective_features().contains(feature)
    }

    /// Check if this license is activated for the given machine.
    pub fn is_activated_for(&self, machine_id: &str) -> bool {
        match &self.machine_id {
            Some(id) => id == machine_id,
            None => false, // Not activated yet
        }
    }
}

/// A license key is the base64-encoded payload + signature.
#[derive(Debug, Clone)]
pub struct LicenseKey {
    pub payload: LicensePayload,
    #[allow(dead_code)]
    signature: Signature,
}

impl LicenseKey {
    #[allow(dead_code)]
    /// Parse and verify a license key string.
    ///
    /// Format: `<base64_payload>.<base64_signature>`
    pub fn parse(key_str: &str) -> Result<Self> {
        let parts: Vec<&str> = key_str.split('.').collect();
        if parts.len() != 2 {
            bail!("invalid license key format: expected '<payload>.<signature>'");
        }

        let payload_bytes = BASE64
            .decode(parts[0])
            .context("invalid base64 in license payload")?;
        let sig_bytes = BASE64
            .decode(parts[1])
            .context("invalid base64 in license signature")?;

        let payload: LicensePayload =
            serde_json::from_slice(&payload_bytes).context("failed to parse license payload")?;

        let signature = Signature::from_slice(&sig_bytes).context("invalid signature length")?;

        // Verify signature
        verifying_key()
            .verify(&payload_bytes, &signature)
            .map_err(|e| anyhow::anyhow!("license signature verification failed: {e}"))?;

        Ok(Self { payload, signature })
    }

    #[allow(dead_code)]
    /// Serialize the key back to string form.
    pub fn to_string(&self) -> Result<String> {
        let payload_bytes =
            serde_json::to_vec(&self.payload).context("failed to serialize license payload")?;
        let payload_b64 = BASE64.encode(&payload_bytes);
        let sig_b64 = BASE64.encode(self.signature.to_bytes());
        Ok(format!("{payload_b64}.{sig_b64}"))
    }

    #[allow(dead_code)]
    /// Check if this license allows the given feature.
    pub fn allows(&self, feature: &str) -> bool {
        self.payload.has_feature(feature)
    }

    /// Check if this license is expired.
    pub fn is_expired(&self) -> bool {
        self.payload.is_expired()
    }
}

// ── Machine fingerprinting ────────────────────────────────────────────────

/// Generate a machine fingerprint from hostname + MAC addresses + CPU info.
/// Used for machine-locking licenses during activation.
pub fn generate_machine_id() -> Result<String> {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let mut hasher = DefaultHasher::new();

    // Hostname
    if let Ok(hostname) = hostname::get() {
        hostname.to_string_lossy().hash(&mut hasher);
    }

    // MAC addresses from /sys/class/net/
    if let Ok(entries) = fs::read_dir("/sys/class/net") {
        let mut macs: Vec<String> = entries
            .filter_map(|e| e.ok())
            .filter_map(|e| e.file_name().to_str().map(String::from))
            .filter(|name| name != "lo")
            .filter_map(|name| {
                let addr_path = format!("/sys/class/net/{name}/address");
                fs::read_to_string(&addr_path)
                    .ok()
                    .map(|s| s.trim().to_string())
            })
            .collect();
        macs.sort();
        for mac in macs {
            mac.hash(&mut hasher);
        }
    }

    // CPU info
    if let Ok(cpuinfo) = fs::read_to_string("/proc/cpuinfo") {
        for line in cpuinfo.lines() {
            if line.starts_with("model name") || line.starts_with("CPU implementer") {
                line.hash(&mut hasher);
                break;
            }
        }
    }

    // Machine ID (systemd)
    if let Ok(id) = fs::read_to_string("/etc/machine-id") {
        id.trim().hash(&mut hasher);
    }

    let hash = hasher.finish();
    Ok(format!("T-{:016x}", hash))
}

// ── License storage ───────────────────────────────────────────────────────

/// Derive a simple obfuscation key from machine fingerprint.
/// Not cryptographic — prevents casual hex-editing of the license file.
fn derive_obfuscation_key() -> [u8; 16] {
    let machine = generate_machine_id().unwrap_or_default();
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    let mut hasher = DefaultHasher::new();
    machine.hash(&mut hasher);
    "talus-license-v1".hash(&mut hasher);
    let h = hasher.finish();
    let mut key = [0u8; 16];
    key[0..8].copy_from_slice(&h.to_le_bytes());
    // Second half from a different hash
    let mut hasher2 = DefaultHasher::new();
    h.hash(&mut hasher2);
    let h2 = hasher2.finish();
    key[8..16].copy_from_slice(&h2.to_le_bytes());
    key
}

/// XOR-encrypt data with a key (symmetric — same function encrypts and decrypts).
fn xor_crypt(data: &[u8], key: &[u8]) -> Vec<u8> {
    data.iter()
        .enumerate()
        .map(|(i, &b)| b ^ key[i % key.len()])
        .collect()
}

/// Cached license state stored on disk.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicenseCache {
    /// The original license key string.
    pub key: String,
    /// Parsed payload.
    pub payload: LicensePayload,
    /// Activation token received from server.
    pub activation_token: Option<String>,
    /// When the token was issued.
    pub activated_at: Option<String>,
    /// Token expiry (if time-limited).
    pub token_expires_at: Option<String>,
}

impl LicenseCache {
    fn path() -> Result<PathBuf> {
        let config_dir = dirs::config_dir()
            .or_else(|| dirs::home_dir().map(|h| h.join(".config")))
            .context("cannot determine config directory")?;
        Ok(config_dir.join("talus").join("license.dat"))
    }

    /// Load cached license from disk (with XOR decryption).
    pub fn load() -> Result<Option<Self>> {
        let path = Self::path()?;
        if !path.exists() {
            return Ok(None);
        }
        let encrypted = fs::read(&path).context("failed to read license cache")?;
        let key = derive_obfuscation_key();
        let decrypted = xor_crypt(&encrypted, &key);
        let data = String::from_utf8(decrypted)
            .context("license file is corrupted (decryption failed)")?;
        let cache: Self = serde_json::from_str(&data).context("failed to parse license cache")?;
        Ok(Some(cache))
    }

    /// Save license cache to disk with XOR encryption and restricted permissions (0600).
    pub fn save(&self) -> Result<()> {
        let path = Self::path()?;
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).context("failed to create config directory")?;
            fs::set_permissions(parent, fs::Permissions::from_mode(0o700))
                .context("failed to set config directory permissions")?;
        }
        let data =
            serde_json::to_string_pretty(self).context("failed to serialize license cache")?;
        let key = derive_obfuscation_key();
        let encrypted = xor_crypt(data.as_bytes(), &key);
        let mut file = fs::File::create(&path).context("failed to create license cache")?;
        file.write_all(&encrypted)
            .context("failed to write license cache")?;
        fs::set_permissions(&path, fs::Permissions::from_mode(0o600))
            .context("failed to set license file permissions")?;
        Ok(())
    }

    /// Delete cached license.
    pub fn clear() -> Result<()> {
        let path = Self::path()?;
        if path.exists() {
            fs::remove_file(&path).context("failed to remove license cache")?;
        }
        if let Some(dir) = dirs::config_dir() {
            let trial_file = dir.join("talus").join(".trial.dat");
            let _ = fs::remove_file(trial_file);
        }
        Ok(())
    }

    /// Backup license to a user-specified path.
    pub fn backup(&self, dest: &Path) -> Result<()> {
        let data =
            serde_json::to_string_pretty(self).context("failed to serialize license for backup")?;
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent).ok();
        }
        fs::write(dest, data).context("failed to write license backup")?;
        // Restrict permissions on backup too
        let _ = fs::set_permissions(dest, fs::Permissions::from_mode(0o600));
        Ok(())
    }

    /// Restore license from a backup file.
    pub fn restore(src: &Path) -> Result<Self> {
        let data = fs::read_to_string(src).context("failed to read license backup")?;
        let cache: Self = serde_json::from_str(&data)
            .context("failed to parse license backup — file may be corrupted")?;
        // Verify the key signature before restoring
        LicenseKey::parse(&cache.key).context("backup contains invalid license key")?;
        cache.save()?;
        Ok(cache)
    }
}

// ── Online activation client ──────────────────────────────────────────────

/// Activation server endpoint (configurable via env or default).
fn activation_server_url() -> String {
    std::env::var("TALUS_LICENSE_SERVER")
        .unwrap_or_else(|_| "https://talus-license-server.metaforicmail.workers.dev".to_string())
}

/// Activation request sent to the server.
#[derive(Serialize)]
struct ActivationRequest {
    license_key: String,
    machine_id: String,
    hostname: String,
    version: String,
}

/// Activation response from the server.
#[derive(Deserialize)]
struct ActivationResponse {
    success: bool,
    token: Option<String>,
    expires_at: Option<String>,
    message: Option<String>,
    #[allow(dead_code)]
    tier: Option<String>,
}

/// Activation rate limiter — max 5 attempts per 5 minutes.
static ACTIVATION_ATTEMPTS: OnceLock<std::sync::Mutex<Vec<std::time::Instant>>> = OnceLock::new();

fn check_activation_rate_limit() -> Result<()> {
    let attempts = ACTIVATION_ATTEMPTS.get_or_init(|| std::sync::Mutex::new(Vec::new()));
    let mut attempts = attempts
        .lock()
        .map_err(|e| anyhow::anyhow!("lock poisoned: {e}"))?;
    let now = std::time::Instant::now();
    // Remove entries older than 5 minutes
    attempts.retain(|t| now.duration_since(*t) < std::time::Duration::from_secs(300));
    if attempts.len() >= 5 {
        let oldest = attempts.first().map(|t| t.elapsed().as_secs()).unwrap_or(0);
        let wait = 300 - oldest;
        bail!("too many activation attempts — try again in {wait}s");
    }
    attempts.push(now);
    Ok(())
}

/// Activate a license key against the online server.
pub fn activate_license(key: &str) -> Result<LicenseCache> {
    // Rate limit activation attempts
    check_activation_rate_limit()?;

    // Parse and verify the key locally first
    let license_key =
        LicenseKey::parse(key).context("license key verification failed — invalid signature")?;

    if license_key.is_expired() {
        audit_log(
            "ACTIVATE_FAILED",
            &license_key.payload.license_id,
            "license expired",
        );
        bail!("license {} has expired", license_key.payload.license_id);
    }

    // Downgrade protection: if currently Enterprise, block Community activation
    if let Ok(Some(ref current)) = LicenseCache::load() {
        if current.payload.tier == LicenseTier::Enterprise
            && license_key.payload.tier == LicenseTier::Community
        {
            audit_log(
                "DOWNGRADE_BLOCKED",
                &license_key.payload.license_id,
                "attempted downgrade from Enterprise",
            );
            bail!("cannot downgrade from Enterprise license (deactivate current license first)");
        }
    }

    let machine_id = generate_machine_id()?;
    let hostname = hostname::get()
        .map(|h| h.to_string_lossy().into_owned())
        .unwrap_or_else(|_| "unknown".into());

    let server_url = activation_server_url();

    // Create HTTP client
    let client = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .build()
        .context("failed to create HTTP client")?;

    let request = ActivationRequest {
        license_key: key.to_string(),
        machine_id: machine_id.clone(),
        hostname,
        version: env!("CARGO_PKG_VERSION").to_string(),
    };

    eprintln!("[talus] contacting activation server: {server_url}");

    let response = client
        .post(format!("{server_url}/api/v1/activate"))
        .json(&request)
        .send()
        .context("failed to connect to activation server")?;

    let status = response.status();
    let body: ActivationResponse = response
        .json()
        .context("failed to parse activation response")?;

    if !status.is_success() || !body.success {
        let msg = body.message.unwrap_or_else(|| "unknown error".into());
        audit_log(
            "ACTIVATE_FAILED",
            &license_key.payload.license_id,
            &format!("{status}: {msg}"),
        );
        bail!("activation failed ({status}): {msg}");
    }

    // Update payload with machine ID
    let mut payload = license_key.payload;
    payload.machine_id = Some(machine_id.clone());

    let cache = LicenseCache {
        key: key.to_string(),
        payload,
        activation_token: body.token,
        activated_at: Some(chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string()),
        token_expires_at: body.expires_at,
    };

    cache.save()?;

    audit_log(
        "ACTIVATED",
        &cache.payload.license_id,
        &format!("machine={machine_id}"),
    );
    eprintln!("[talus] ✓ license activated successfully");
    Ok(cache)
}

/// Deactivate a license (release machine binding).
pub fn deactivate_license() -> Result<()> {
    let cache = LicenseCache::load()?.context("no license found — nothing to deactivate")?;

    if let Some(ref token) = cache.activation_token {
        let server_url = activation_server_url();
        let client = reqwest::blocking::Client::builder()
            .timeout(std::time::Duration::from_secs(15))
            .build()
            .context("failed to create HTTP client")?;

        let _ = client
            .post(format!("{server_url}/api/v1/deactivate"))
            .json(&serde_json::json!({
                "license_id": cache.payload.license_id,
                "token": token,
            }))
            .send();
    }

    audit_log(
        "DEACTIVATED",
        &cache.payload.license_id,
        "user deactivation",
    );
    LicenseCache::clear()?;
    eprintln!("[talus] ✓ license deactivated");
    Ok(())
}

/// Verify the current cached license is still valid.
pub fn verify_cached_license() -> Result<LicenseCache> {
    let cache = LicenseCache::load()?
        .context("no license found — run `talus license activate <KEY>` to activate")?;

    // ── Signed-key binding ────────────────────────────────────────────
    // Re-verify the stored key's Ed25519 signature and bind the cached
    // payload to it. Only `machine_id` may differ (it is added locally
    // after activation). Any other divergence — tier, expiry, features,
    // seat_count, organization — means the local cache was tampered with.
    match LicenseKey::parse(&cache.key) {
        Ok(signed) => {
            let p = &signed.payload;
            let c = &cache.payload;
            let diverged = p.license_id != c.license_id
                || p.tier != c.tier
                || p.features != c.features
                || p.max_nodes != c.max_nodes
                || p.expires_at != c.expires_at
                || p.organization != c.organization
                || p.seat_count != c.seat_count;
            if diverged {
                audit_log(
                    "CACHE_TAMPERED",
                    &c.license_id,
                    "cached payload diverges from the signed license key",
                );
                bail!("license cache has been tampered with — re-activation required");
            }
        }
        Err(e) => {
            audit_log(
                "CACHE_TAMPERED",
                &cache.payload.license_id,
                "stored license key failed signature verification",
            );
            bail!("license key in cache failed verification ({e}) — re-activation required");
        }
    }

    // Verify config file integrity
    if !verify_config_integrity().unwrap_or(false) {
        audit_log(
            "CONFIG_TAMPERED",
            &cache.payload.license_id,
            "config integrity check failed",
        );
        bail!("config files have been tampered with — re-activate required");
    }

    // Check expiry
    if cache.payload.is_expired() {
        // Offline grace period: allow 30 days after last server contact
        if is_within_offline_grace(&cache) {
            audit_log(
                "EXPIRED_GRACE",
                &cache.payload.license_id,
                "license expired but within offline grace period",
            );
            eprintln!("[talus] ⚠ license expired — running in offline grace mode");
        } else {
            audit_log("EXPIRED", &cache.payload.license_id, "license expired");
            bail!("license {} has expired", cache.payload.license_id);
        }
    }

    // Check token expiry
    if let Some(ref expires) = cache.token_expires_at {
        if let Ok(expiry) = chrono::NaiveDateTime::parse_from_str(expires, "%Y-%m-%dT%H:%M:%SZ") {
            if chrono::Utc::now().naive_utc() > expiry {
                // Offline grace for token expiry too
                if is_within_offline_grace(&cache) {
                    audit_log(
                        "TOKEN_EXPIRED_GRACE",
                        &cache.payload.license_id,
                        "token expired but within offline grace period",
                    );
                    eprintln!("[talus] ⚠ activation token expired — running in offline grace mode");
                } else {
                    audit_log(
                        "TOKEN_EXPIRED",
                        &cache.payload.license_id,
                        "activation token expired",
                    );
                    bail!("activation token has expired — please re-activate");
                }
            }
        }
    }

    // Verify machine binding
    let current_machine = generate_machine_id()?;
    if !cache.payload.is_activated_for(&current_machine) {
        audit_log(
            "MISMATCH",
            &cache.payload.license_id,
            &format!(
                "machine mismatch: expected {}",
                cache.payload.machine_id.as_deref().unwrap_or("?")
            ),
        );
        bail!(
            "license is activated for a different machine (expected: {})",
            cache.payload.machine_id.as_deref().unwrap_or("?")
        );
    }

    // Save integrity hash after successful verification
    let _ = save_config_integrity();

    Ok(cache)
}

// ── Audit logging ─────────────────────────────────────────────────────────

/// Append an entry to the license audit log.
/// Compute SHA-256 hash of data (returns hex string).
fn sha256_hex(data: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(data);
    let result = hasher.finalize();
    result.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Delegate to the audit module for signed hash-chain logging.
fn audit_log(event: &str, license_id: &str, detail: &str) {
    crate::audit::audit_log(event, license_id, detail);
}

/// Verify the integrity of the audit log (hash chain).
#[allow(dead_code)]
pub fn verify_audit_log() -> Result<u64> {
    crate::audit::verify_audit_log()
}

/// Read the last N entries from the audit log.
pub fn read_audit_log(max_entries: usize) -> Vec<String> {
    crate::audit::read_audit_log(max_entries)
}

/// Get license health status as a JSON-serializable struct.
#[cfg(feature = "web")]
pub fn license_health() -> LicenseHealth {
    match LicenseCache::load() {
        Ok(Some(cache)) => {
            let expired = cache.payload.is_expired();
            let days = cache
                .payload
                .expires_at
                .as_ref()
                .and_then(|exp| days_remaining(exp));
            let current_machine = generate_machine_id().ok();
            let machine_match = current_machine
                .as_ref()
                .map(|m| cache.payload.is_activated_for(m))
                .unwrap_or(false);
            let features: Vec<String> = cache.payload.effective_features().into_iter().collect();
            LicenseHealth {
                status: if expired {
                    "expired".into()
                } else if !machine_match {
                    "machine_mismatch".into()
                } else {
                    "valid".into()
                },
                tier: cache.payload.tier.to_string(),
                license_id: cache.payload.license_id,
                organization: cache.payload.organization,
                expired,
                days_remaining: days,
                activated: cache.activation_token.is_some(),
                machine_bound: cache.payload.machine_id.is_some(),
                features,
            }
        }
        Ok(None) => LicenseHealth {
            status: "no_license".into(),
            tier: "community".into(),
            license_id: String::new(),
            organization: None,
            expired: false,
            days_remaining: None,
            activated: false,
            machine_bound: false,
            features: LicenseTier::Community.default_features(),
        },
        Err(_) => LicenseHealth {
            status: "error".into(),
            tier: "community".into(),
            license_id: String::new(),
            organization: None,
            expired: false,
            days_remaining: None,
            activated: false,
            machine_bound: false,
            features: LicenseTier::Community.default_features(),
        },
    }
}

/// License health status for API responses.
#[derive(Serialize)]
#[cfg(feature = "web")]
pub struct LicenseHealth {
    pub status: String,
    pub tier: String,
    pub license_id: String,
    pub organization: Option<String>,
    pub expired: bool,
    pub days_remaining: Option<i64>,
    pub activated: bool,
    pub machine_bound: bool,
    pub features: Vec<String>,
}

// ── Feature gating ────────────────────────────────────────────────────────

/// Runtime license state used throughout the application.
#[derive(Debug, Clone)]
pub struct LicenseState {
    pub tier: LicenseTier,
    features: HashSet<String>,
    #[allow(dead_code)]
    pub license_id: Option<String>,
    #[allow(dead_code)]
    pub organization: Option<String>,
    pub is_activated: bool,
}

impl LicenseState {
    /// No license — community defaults.
    pub fn community() -> Self {
        Self {
            tier: LicenseTier::Community,
            features: LicenseTier::Community
                .default_features()
                .into_iter()
                .collect(),
            license_id: None,
            organization: None,
            is_activated: false,
        }
    }

    /// 30-day Enterprise trial.
    pub fn trial() -> Self {
        Self {
            tier: LicenseTier::Enterprise,
            features: LicenseTier::Enterprise
                .default_features()
                .into_iter()
                .collect(),
            license_id: Some("TRIAL-30D".into()),
            organization: Some("Enterprise Trial".into()),
            is_activated: false,
        }
    }

    /// Create from a verified cached license.
    pub fn from_cache(cache: &LicenseCache) -> Self {
        Self {
            tier: cache.payload.tier.clone(),
            features: cache.payload.effective_features(),
            license_id: Some(cache.payload.license_id.clone()),
            organization: cache.payload.organization.clone(),
            is_activated: cache.activation_token.is_some(),
        }
    }

    /// Check if a specific feature is enabled.
    pub fn allows(&self, feature: &str) -> bool {
        self.features.contains(feature)
    }

    /// Get the tier display name.
    pub fn tier_name(&self) -> &str {
        self.tier.display_name()
    }

    #[allow(dead_code)]
    /// Get all enabled features as a sorted list.
    pub fn feature_list(&self) -> Vec<String> {
        let mut features: Vec<String> = self.features.iter().cloned().collect();
        features.sort();
        features
    }
}

/// Cached license state (initialized once at startup).
static CACHED_STATE: OnceLock<LicenseState> = OnceLock::new();

/// Get the cached license state (fast, no re-parsing).
/// Must call `init_license()` first at startup.
#[allow(dead_code)]
pub fn get_license_state() -> &'static LicenseState {
    CACHED_STATE.get_or_init(LicenseState::community)
}

/// Initialize license state at startup.
/// Checks for cached license, falls back to community mode.
pub fn init_license() -> LicenseState {
    // Verify binary integrity (detect key tampering)
    if !verify_key_integrity() {
        eprintln!("[talus] ⚠ WARNING: binary integrity check failed — license key may have been tampered with");
        let state = LicenseState::community();
        let _ = CACHED_STATE.set(state.clone());
        return state;
    }

    let state = match verify_cached_license() {
        Ok(cache) => {
            eprintln!(
                "[talus] license: {} ({})",
                cache.payload.license_id, cache.payload.tier
            );
            if let Some(ref org) = cache.payload.organization {
                eprintln!("[talus] organization: {org}");
            }
            // Expiry warnings
            if let Some(ref exp) = cache.payload.expires_at {
                if let Some(days) = days_remaining(exp) {
                    if days <= 0 {
                        eprintln!("[talus] ⚠ LICENSE EXPIRED — running in community mode");
                        LicenseState::community()
                    } else if days <= 7 {
                        eprintln!("[talus] ⚠ WARNING: license expires in {days} days!");
                        LicenseState::from_cache(&cache)
                    } else if days <= 30 {
                        eprintln!("[talus] ℹ license expires in {days} days");
                        LicenseState::from_cache(&cache)
                    } else {
                        LicenseState::from_cache(&cache)
                    }
                } else {
                    LicenseState::from_cache(&cache)
                }
            } else {
                LicenseState::from_cache(&cache)
            }
        }
        Err(_) => {
            let trial = is_trial_active();
            if trial {
                eprintln!("[talus] license: Enterprise Trial (30 days)");
                LicenseState::trial()
            } else {
                eprintln!("[talus] license: community mode");
                LicenseState::community()
            }
        }
    };
    let _ = CACHED_STATE.set(state.clone());
    state
}

/// Verify the embedded public key hasn't been tampered with.
/// Returns true if the key is intact.
fn verify_key_integrity() -> bool {
    let current_checksum = xor_checksum(&PUBLIC_KEY_BYTES);
    current_checksum == KEY_CHECKSUM
}

// ── Offline grace period ──────────────────────────────────────────────────

/// Maximum offline grace period in days.
/// License remains valid for this many days after last server contact.
const OFFLINE_GRACE_DAYS: i64 = 30;

/// Check if the license is within offline grace period.
/// Returns true if the license was recently verified online.
fn is_within_offline_grace(cache: &LicenseCache) -> bool {
    if let Some(ref at) = cache.activated_at {
        if let Ok(last_contact) = chrono::NaiveDateTime::parse_from_str(at, "%Y-%m-%dT%H:%M:%SZ") {
            let elapsed = chrono::Utc::now().naive_utc() - last_contact;
            return elapsed.num_days() <= OFFLINE_GRACE_DAYS;
        }
    }
    false
}

// ── Config integrity ──────────────────────────────────────────────────────

/// Protect config files with HMAC integrity checking.
fn config_integrity_path() -> Option<PathBuf> {
    dirs::config_dir().map(|d| d.join("talus").join(".integrity.hmac"))
}

/// Save HMAC of all config files for integrity checking.
pub fn save_config_integrity() -> Result<()> {
    let hmac_path = match config_integrity_path() {
        Some(p) => p,
        None => return Ok(()),
    };
    let config_dir = match dirs::config_dir() {
        Some(d) => d.join("talus"),
        None => return Ok(()),
    };

    let mut files_hash = Vec::new();
    // Hash license file
    let license_path = config_dir.join("license.dat");
    if let Ok(data) = fs::read(&license_path) {
        files_hash.extend_from_slice(sha256_hex(&data).as_bytes());
    }
    // Hash trial file
    let trial_path = config_dir.join(".trial.dat");
    if let Ok(data) = fs::read(&trial_path) {
        files_hash.extend_from_slice(sha256_hex(&data).as_bytes());
    }

    let key = derive_obfuscation_key();
    let hmac = sha256_hex(&[&key[..], &files_hash].concat());

    if let Some(parent) = hmac_path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let _ = fs::write(&hmac_path, &hmac);
    let _ = fs::set_permissions(&hmac_path, fs::Permissions::from_mode(0o600));
    Ok(())
}

/// Verify config file integrity.
pub fn verify_config_integrity() -> Result<bool> {
    let hmac_path = match config_integrity_path() {
        Some(p) => p,
        None => return Ok(true),
    };
    if !hmac_path.exists() {
        return Ok(true); // No integrity file = first run
    }
    let stored_hmac = fs::read_to_string(&hmac_path).context("failed to read integrity file")?;
    let config_dir = dirs::config_dir()
        .context("cannot determine config directory")?
        .join("talus");

    let mut files_hash = Vec::new();
    let license_path = config_dir.join("license.dat");
    if let Ok(data) = fs::read(&license_path) {
        files_hash.extend_from_slice(sha256_hex(&data).as_bytes());
    }
    let trial_path = config_dir.join(".trial.dat");
    if let Ok(data) = fs::read(&trial_path) {
        files_hash.extend_from_slice(sha256_hex(&data).as_bytes());
    }

    let key = derive_obfuscation_key();
    let expected = sha256_hex(&[&key[..], &files_hash].concat());

    Ok(stored_hmac.trim() == expected)
}

/// Check if a 30-day trial is active.
/// Trial starts on first run and lasts 30 days.
/// Uses hidden file with restricted permissions to resist casual tampering.
fn is_trial_active() -> bool {
    let marker = match dirs::config_dir() {
        Some(dir) => dir.join("talus"),
        None => return false,
    };
    let trial_file = marker.join(".trial.dat");

    if trial_file.exists() {
        // Check if trial has expired
        if let Ok(data) = fs::read_to_string(&trial_file) {
            if let Ok(trial) = serde_json::from_str::<TrialData>(&data) {
                if let Ok(start) =
                    chrono::NaiveDateTime::parse_from_str(&trial.started_at, "%Y-%m-%dT%H:%M:%SZ")
                {
                    let elapsed = chrono::Utc::now().naive_utc() - start;
                    if elapsed.num_days() < 30 {
                        // Verify the integrity tag: detects edited start dates
                        // and trial files copied from other machines.
                        let expected = compute_trial_checksum(&trial.started_at);
                        if trial.checksum == expected {
                            return true;
                        }
                        audit_log("TRIAL_TAMPERED", "TRIAL-30D", "trial checksum mismatch");
                        let _ = fs::remove_file(&trial_file);
                        return false;
                    }
                    // Trial expired — clean up
                    audit_log("TRIAL_EXPIRED", "TRIAL-30D", "trial ended");
                    let _ = fs::remove_file(&trial_file);
                    return false;
                }
            }
        }
        // Corrupted trial file — treat as no trial
        let _ = fs::remove_file(&trial_file);
        false
    } else {
        // First run — start trial
        let _ = fs::create_dir_all(&marker);
        let started_at = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string();
        let trial = TrialData {
            checksum: compute_trial_checksum(&started_at),
            started_at,
        };
        if let Ok(data) = serde_json::to_string_pretty(&trial) {
            if let Ok(mut file) = fs::File::create(&trial_file) {
                let _ = file.write_all(data.as_bytes());
                // Set permissions to 0600 (owner-only)
                let _ = fs::set_permissions(&trial_file, fs::Permissions::from_mode(0o600));
            }
        }
        eprintln!("[talus] 30-day Enterprise trial started!");
        audit_log(
            "TRIAL_STARTED",
            "TRIAL-30D",
            "first run — 30-day trial begins",
        );
        true
    }
}

/// Compute an integrity tag for the trial record to detect tampering.
///
/// SHA-256 over: public-key checksum ‖ machine fingerprint ‖ started_at.
/// Ties the trial record to this binary AND this machine, so the trial file
/// cannot be edited (extend the start date) or copied from another machine
/// without the tag mismatching. The machine fingerprint is public, so this is
/// an integrity tag rather than a true MAC — it resists casual tampering,
/// which is the documented threat model for the local trial marker.
fn compute_trial_checksum(started_at: &str) -> String {
    let machine = generate_machine_id().unwrap_or_default();
    let key = KEY_CHECKSUM.to_le_bytes();
    let data = [&key[..], machine.as_bytes(), started_at.as_bytes()].concat();
    sha256_hex(&data)[..32].to_string()
}

#[derive(Serialize, Deserialize)]
struct TrialData {
    started_at: String,
    #[serde(default)]
    checksum: String,
}

// ── License info display ──────────────────────────────────────────────────

/// Days remaining before license expires (or 0 if expired/perpetual).
fn days_remaining(expires: &str) -> Option<i64> {
    chrono::NaiveDateTime::parse_from_str(expires, "%Y-%m-%dT%H:%M:%SZ")
        .ok()
        .map(|exp| {
            let now = chrono::Utc::now().naive_utc();
            (exp - now).num_days()
        })
}

/// Export license as JSON for programmatic integration.
pub fn export_license_json() -> Result<String> {
    let cache = LicenseCache::load()?.context("no license found")?;

    let output = serde_json::json!({
        "license_id": cache.payload.license_id,
        "tier": cache.payload.tier,
        "organization": cache.payload.organization,
        "issued_at": cache.payload.issued_at,
        "expires_at": cache.payload.expires_at,
        "machine_id": cache.payload.machine_id,
        "activated": cache.activation_token.is_some(),
        "activated_at": cache.activated_at,
        "features": cache.payload.effective_features().into_iter().collect::<Vec<_>>(),
    });

    serde_json::to_string_pretty(&output).context("failed to serialize license")
}

/// Transfer license to a different machine.
/// Deactivates on current machine, user must reactivate on the new one.
pub fn transfer_license() -> Result<()> {
    let cache = LicenseCache::load()?.context("no license found — nothing to transfer")?;

    eprintln!("[talus] license transfer");
    eprintln!("[talus] license ID: {}", cache.payload.license_id);
    eprintln!();

    // Show the raw key so user can copy it
    eprintln!("[talus] Your license key:");
    eprintln!();
    eprintln!("  {}", cache.key);
    eprintln!();
    eprintln!("[talus] To transfer:");
    eprintln!("  1. On the new machine, run: talus license activate <KEY>");
    eprintln!("  2. The key above is your license key");
    eprintln!();

    // Deactivate locally
    LicenseCache::clear()?;
    eprintln!("[talus] ✓ License deactivated on this machine");
    Ok(())
}

/// Print license information to stdout.
pub fn show_license_info() -> Result<()> {
    let r = "\x1b[0m"; // reset
    let c = "\x1b[36m"; // cyan
    let g = "\x1b[32m"; // green
    let y = "\x1b[33m"; // yellow
    let d = "\x1b[31m"; // red
    let dim = "\x1b[2m"; // dim
    let w: &str = ""; // width placeholder
    let _ = w; // suppress unused

    match LicenseCache::load()? {
        Some(cache) => {
            let tc = match cache.payload.tier {
                LicenseTier::Enterprise => g,
                LicenseTier::Community => y,
            };
            let icon = match cache.payload.tier {
                LicenseTier::Enterprise => "◆",
                LicenseTier::Community => "◇",
            };

            println!();
            println!("  {tc}╔══════════════════════════════════════════════════╗{r}");
            println!(
                "  {tc}║{r}  {icon} {tc}TALUS LICENSE{r}                              {tc}║{r}"
            );
            println!("  {tc}╠══════════════════════════════════════════════════╣{r}");
            println!(
                "  {tc}║{r}  License ID:   {:<33}{tc}║{r}",
                cache.payload.license_id
            );
            println!(
                "  {tc}║{r}  Tier:         {tc}{:<33}{r}{tc}║{r}",
                cache.payload.tier
            );
            if let Some(ref org) = cache.payload.organization {
                println!("  {tc}║{r}  Organization: {:<33}{tc}║{r}", org);
            }
            println!(
                "  {tc}║{r}  Issued:       {:<33}{tc}║{r}",
                cache.payload.issued_at
            );

            // Expiry
            if let Some(ref exp) = cache.payload.expires_at {
                if cache.payload.is_expired() {
                    println!("  {tc}║{r}  Expires:      {d}{exp}{r}                  {tc}║{r}");
                    println!(
                        "  {tc}║{r}  Status:       {d}✗ EXPIRED{r}                        {tc}║{r}"
                    );
                } else if let Some(days) = days_remaining(exp) {
                    let dc = if days <= 30 {
                        d
                    } else if days <= 90 {
                        y
                    } else {
                        g
                    };
                    println!("  {tc}║{r}  Expires:      {dc}{exp}{r}                  {tc}║{r}");
                    println!("  {tc}║{r}  Status:       {dc}✓ VALID — {days} days remaining{r}     {tc}║{r}");
                } else {
                    println!("  {tc}║{r}  Expires:      {:<33}{tc}║{r}", exp);
                    println!("  {tc}║{r}  Status:       {g}✓ VALID{r}                            {tc}║{r}");
                }
            } else {
                println!(
                    "  {tc}║{r}  Expires:      {:<33}{tc}║{r}",
                    "never (perpetual)"
                );
                println!(
                    "  {tc}║{r}  Status:       {g}✓ VALID (perpetual){r}              {tc}║{r}"
                );
            }

            // Machine binding
            if let Some(ref machine) = cache.payload.machine_id {
                println!("  {tc}║{r}  Machine ID:   {:<33}{tc}║{r}", machine);
            }

            // Activation
            if let Some(ref _token) = cache.activation_token {
                println!(
                    "  {tc}║{r}  Activation:   {g}✓ activated{r}                       {tc}║{r}"
                );
                if let Some(ref at) = cache.activated_at {
                    println!("  {tc}║{r}  Activated at: {:<33}{tc}║{r}", at);
                }
                if let Some(ref exp) = cache.token_expires_at {
                    println!("  {tc}║{r}  Token expires:{:<33}{tc}║{r}", exp);
                }
            } else {
                println!(
                    "  {tc}║{r}  Activation:   {y}✗ not activated (offline){r}       {tc}║{r}"
                );
            }

            // Features
            let features = cache.payload.effective_features();
            let mut feature_list: Vec<String> = features.into_iter().collect();
            feature_list.sort();
            println!(
                "  {tc}║{r}  Features:     {:<33}{tc}║{r}",
                feature_list.join(", ")
            );
            println!("  {tc}╚══════════════════════════════════════════════════╝{r}");
            println!();
            Ok(())
        }
        None => {
            println!();
            println!("  {c}╔══════════════════════════════════════════════════╗{r}");
            println!("  {c}║{r}  ◇ {c}TALUS LICENSE{r}                              {c}║{r}");
            println!("  {c}╠══════════════════════════════════════════════════╣{r}");
            println!("  {c}║{r}                                                  {c}║{r}");
            println!("  {c}║{r}  No license found. Running in {y}Community{r} mode.   {c}║{r}");
            println!("  {c}║{r}                                                  {c}║{r}");
            println!("  {c}║{r}  {g}Community features:{r}                              {c}║{r}");
            println!("  {c}║{r}    • TUI dashboard (7 panels)                    {c}║{r}");
            println!("  {c}║{r}    • JSON / plain text output                    {c}║{r}");
            println!("  {c}║{r}    • Real-time eBPF monitoring                   {c}║{r}");
            println!("  {c}║{r}    • Ransomware detection alerts                 {c}║{r}");
            println!("  {c}║{r}                                                  {c}║{r}");
            println!("  {c}║{r}  {y}Enterprise upgrade:{r}                              {c}║{r}");
            println!("  {c}║{r}    • Web dashboard & REST API                   {c}║{r}");
            println!("  {c}║{r}    • Auto-kill (EDR response mode)              {c}║{r}");
            println!("  {c}║{r}    • Kafka streaming                            {c}║{r}");
            println!("  {c}║{r}    • ClickHouse analytics                       {c}║{r}");
            println!("  {c}║{r}    • MemGraph process graphs                    {c}║{r}");
            println!("  {c}║{r}    • C FFI library                              {c}║{r}");
            println!("  {c}║{r}    • Priority support                           {c}║{r}");
            println!("  {c}║{r}                                                  {c}║{r}");
            println!("  {c}║{r}  {dim}Activate:  talus license activate <KEY>{r}       {c}║{r}");
            println!("  {c}║{r}  {dim}More info:  https://talus.io/enterprise{r}         {c}║{r}");
            println!("  {c}║{r}                                                  {c}║{r}");
            println!("  {c}╚══════════════════════════════════════════════════╝{r}");
            println!();
            Ok(())
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn license_tier_default_features() {
        let community = LicenseTier::Community;
        let features = community.default_features();
        assert!(features.contains(&"tui".to_string()));
        assert!(features.contains(&"json".to_string()));
        assert!(!features.contains(&"web".to_string()));
        assert!(!features.contains(&"auto_kill".to_string()));

        let enterprise = LicenseTier::Enterprise;
        let features = enterprise.default_features();
        assert!(features.contains(&"web".to_string()));
        assert!(features.contains(&"auto_kill".to_string()));
        assert!(features.contains(&"kafka".to_string()));
    }

    #[test]
    fn license_payload_not_expired_when_no_expiry() {
        let payload = LicensePayload {
            license_id: "TALUS-TEST".into(),
            tier: LicenseTier::Enterprise,
            features: None,
            max_nodes: 0,
            expires_at: None,
            issued_at: "2026-01-01T00:00:00Z".into(),
            machine_id: None,
            organization: None,
            seat_count: 1,
        };
        assert!(!payload.is_expired());
    }

    #[test]
    fn license_payload_expired_when_past_expiry() {
        let payload = LicensePayload {
            license_id: "TALUS-TEST".into(),
            tier: LicenseTier::Enterprise,
            features: None,
            max_nodes: 0,
            expires_at: Some("2020-01-01T00:00:00Z".into()),
            issued_at: "2019-01-01T00:00:00Z".into(),
            machine_id: None,
            organization: None,
            seat_count: 1,
        };
        assert!(payload.is_expired());
    }

    #[test]
    fn license_payload_not_expired_when_future_expiry() {
        let payload = LicensePayload {
            license_id: "TALUS-TEST".into(),
            tier: LicenseTier::Enterprise,
            features: None,
            max_nodes: 0,
            expires_at: Some("2099-12-31T23:59:59Z".into()),
            issued_at: "2026-01-01T00:00:00Z".into(),
            machine_id: None,
            organization: None,
            seat_count: 1,
        };
        assert!(!payload.is_expired());
    }

    #[test]
    fn license_payload_effective_features_override() {
        let payload = LicensePayload {
            license_id: "TALUS-TEST".into(),
            tier: LicenseTier::Enterprise,
            features: Some(vec!["tui".into(), "web".into()]),
            max_nodes: 0,
            expires_at: None,
            issued_at: "2026-01-01T00:00:00Z".into(),
            machine_id: None,
            organization: None,
            seat_count: 1,
        };
        let features = payload.effective_features();
        assert!(features.contains("tui"));
        assert!(features.contains("web"));
        assert!(!features.contains("auto_kill")); // Not in explicit list
    }

    #[test]
    fn license_payload_has_feature() {
        let payload = LicensePayload {
            license_id: "TALUS-TEST".into(),
            tier: LicenseTier::Enterprise,
            features: None,
            max_nodes: 0,
            expires_at: None,
            issued_at: "2026-01-01T00:00:00Z".into(),
            machine_id: None,
            organization: None,
            seat_count: 1,
        };
        assert!(payload.has_feature("tui"));
        assert!(payload.has_feature("web"));
        assert!(!payload.has_feature("nonexistent"));
    }

    #[test]
    fn license_state_community_defaults() {
        let state = LicenseState::community();
        assert_eq!(state.tier, LicenseTier::Community);
        assert!(state.allows("tui"));
        assert!(!state.allows("web"));
        assert!(!state.allows("auto_kill"));
        assert!(!state.is_activated);
        assert!(state.license_id.is_none());
    }

    #[test]
    fn license_state_from_cache() {
        let cache = LicenseCache {
            key: "test".into(),
            payload: LicensePayload {
                license_id: "TALUS-ENT-001".into(),
                tier: LicenseTier::Enterprise,
                features: None,
                max_nodes: 0,
                expires_at: None,
                issued_at: "2026-01-01T00:00:00Z".into(),
                machine_id: Some("T-abc123".into()),
                organization: Some("Acme Corp".into()),
                seat_count: 1,
            },
            activation_token: Some("token123".into()),
            activated_at: None,
            token_expires_at: None,
        };
        let state = LicenseState::from_cache(&cache);
        assert_eq!(state.tier, LicenseTier::Enterprise);
        assert!(state.allows("web"));
        assert!(state.allows("auto_kill"));
        assert!(state.is_activated);
        assert_eq!(state.license_id.as_deref(), Some("TALUS-ENT-001"));
        assert_eq!(state.organization.as_deref(), Some("Acme Corp"));
    }

    #[test]
    fn machine_id_generation() {
        let id1 = generate_machine_id().unwrap();
        let id2 = generate_machine_id().unwrap();
        assert_eq!(id1, id2, "machine ID should be deterministic");
        assert!(id1.starts_with("T-"));
    }

    #[test]
    fn license_key_parse_invalid_format() {
        assert!(LicenseKey::parse("invalid").is_err());
        assert!(LicenseKey::parse("a.b.c").is_err());
    }

    #[test]
    fn license_key_parse_invalid_base64() {
        assert!(LicenseKey::parse("!!!.!!!").is_err());
    }

    #[test]
    fn license_cache_path_deterministic() {
        let path1 = LicenseCache::path().unwrap();
        let path2 = LicenseCache::path().unwrap();
        assert_eq!(path1, path2);
    }

    #[test]
    fn license_tier_display() {
        assert_eq!(LicenseTier::Community.to_string(), "Community");
        assert_eq!(LicenseTier::Enterprise.to_string(), "Enterprise");
    }

    #[test]
    fn license_state_feature_list_sorted() {
        let state = LicenseState::community();
        let features = state.feature_list();
        let mut sorted = features.clone();
        sorted.sort();
        assert_eq!(features, sorted);
    }

    #[test]
    fn license_state_trial_has_all_features() {
        let state = LicenseState::trial();
        assert_eq!(state.tier, LicenseTier::Enterprise);
        assert!(state.allows("web"));
        assert!(state.allows("auto_kill"));
        assert!(state.allows("kafka"));
        assert!(state.allows("clickhouse"));
        assert!(state.allows("memgraph"));
        assert!(state.allows("ffi"));
        assert_eq!(state.license_id.as_deref(), Some("TRIAL-30D"));
        assert!(!state.is_activated);
    }

    #[test]
    fn xor_checksum_identity() {
        // XOR of empty is 0
        assert_eq!(xor_checksum(&[]), 0);
        // XOR of single byte is itself
        assert_eq!(xor_checksum(&[0x42]), 0x42);
        // XOR is commutative and associative
        assert_eq!(
            xor_checksum(&[0x01, 0x02, 0x03]),
            xor_checksum(&[0x03, 0x01, 0x02])
        );
    }

    #[test]
    fn key_integrity_check() {
        // The real key should pass
        assert!(verify_key_integrity());
    }

    #[test]
    fn license_payload_max_nodes() {
        let payload = LicensePayload {
            license_id: "TALUS-TEST".into(),
            tier: LicenseTier::Enterprise,
            features: None,
            max_nodes: 42,
            expires_at: None,
            issued_at: "2026-01-01T00:00:00Z".into(),
            machine_id: None,
            organization: None,
            seat_count: 1,
        };
        assert_eq!(payload.max_nodes, 42);
    }

    #[test]
    fn license_payload_machine_binding() {
        let payload = LicensePayload {
            license_id: "TALUS-TEST".into(),
            tier: LicenseTier::Enterprise,
            features: None,
            max_nodes: 0,
            expires_at: None,
            issued_at: "2026-01-01T00:00:00Z".into(),
            machine_id: Some("T-abc123".into()),
            organization: None,
            seat_count: 1,
        };
        assert!(payload.is_activated_for("T-abc123"));
        assert!(!payload.is_activated_for("T-different"));
    }

    #[test]
    fn days_remaining_future() {
        let result = days_remaining("2099-12-31T23:59:59Z");
        assert!(result.is_some());
        assert!(result.unwrap() > 365 * 50);
    }

    #[test]
    fn days_remaining_past() {
        let result = days_remaining("2020-01-01T00:00:00Z");
        assert!(result.is_some());
        assert!(result.unwrap() < 0);
    }

    #[test]
    fn license_key_parse_and_roundtrip_structure() {
        // Test that the parse function properly validates structure
        assert!(LicenseKey::parse("").is_err());
        assert!(LicenseKey::parse("abc").is_err());
        assert!(LicenseKey::parse("abc.def.ghi").is_err());
    }

    #[test]
    fn license_payload_serialization_roundtrip() {
        let payload = LicensePayload {
            license_id: "TALUS-RT-001".into(),
            tier: LicenseTier::Enterprise,
            features: Some(vec!["web".into(), "auto_kill".into()]),
            max_nodes: 10,
            expires_at: Some("2027-06-30T00:00:00Z".into()),
            issued_at: "2026-01-01T00:00:00Z".into(),
            machine_id: Some("T-test".into()),
            organization: Some("Test Corp".into()),
            seat_count: 1,
        };
        let json = serde_json::to_string(&payload).unwrap();
        let restored: LicensePayload = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.license_id, "TALUS-RT-001");
        assert_eq!(restored.tier, LicenseTier::Enterprise);
        assert_eq!(restored.max_nodes, 10);
        assert!(restored.features.unwrap().contains(&"web".to_string()));
        assert_eq!(restored.organization.as_deref(), Some("Test Corp"));
    }

    // ── Integration tests ──────────────────────────────────────────────

    #[test]
    fn obfuscation_key_is_deterministic() {
        let k1 = derive_obfuscation_key();
        let k2 = derive_obfuscation_key();
        assert_eq!(k1, k2, "obfuscation key must be deterministic");
    }

    #[test]
    fn xor_crypt_is_symmetric() {
        let key = derive_obfuscation_key();
        let original = b"hello talus license data 1234567890";
        let encrypted = xor_crypt(original, &key);
        let decrypted = xor_crypt(&encrypted, &key);
        assert_eq!(decrypted, original, "XOR must be symmetric");
    }

    #[test]
    fn xor_crypt_differs_from_original() {
        let key = derive_obfuscation_key();
        let original = b"license data";
        let encrypted = xor_crypt(original, &key);
        // Should be encrypted (different from original) unless key happens to be all zeros
        assert_ne!(encrypted, original, "encryption should change the data");
    }

    #[test]
    fn xor_crypt_empty_data() {
        let key = derive_obfuscation_key();
        let empty = xor_crypt(b"", &key);
        assert!(empty.is_empty());
    }

    #[test]
    fn license_cache_save_load_roundtrip() {
        // Create a temporary directory for the test
        let tmp = std::env::temp_dir().join("talus_test_license");
        let _ = fs::remove_dir_all(&tmp);
        fs::create_dir_all(&tmp).unwrap();

        // We can't easily test the real path, but we can test the serialization
        let cache = LicenseCache {
            key: "test.key.data".into(),
            payload: LicensePayload {
                license_id: "TALUS-TEST-CACHE".into(),
                tier: LicenseTier::Enterprise,
                features: None,
                max_nodes: 0,
                expires_at: None,
                issued_at: "2026-01-01T00:00:00Z".into(),
                machine_id: Some("T-test123".into()),
                organization: Some("Test Org".into()),
                seat_count: 1,
            },
            activation_token: Some("token-abc".into()),
            activated_at: Some("2026-08-30T00:00:00Z".into()),
            token_expires_at: None,
        };

        // Test serialization
        let json = serde_json::to_string(&cache).unwrap();
        let restored: LicenseCache = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.payload.license_id, "TALUS-TEST-CACHE");
        assert_eq!(restored.activation_token.as_deref(), Some("token-abc"));
        assert_eq!(restored.payload.organization.as_deref(), Some("Test Org"));

        let _ = fs::remove_dir_all(&tmp);
    }

    #[test]
    #[cfg(feature = "web")]
    fn license_health_struct_serializes() {
        // Test that LicenseHealth can be serialized (used by web API)
        let health = LicenseHealth {
            status: "valid".into(),
            tier: "enterprise".into(),
            license_id: "TALUS-001".into(),
            organization: Some("Corp".into()),
            expired: false,
            days_remaining: Some(365),
            activated: true,
            machine_bound: true,
            features: vec!["web".into(), "auto_kill".into()],
        };
        let json = serde_json::to_string(&health).unwrap();
        assert!(json.contains("enterprise"));
        assert!(json.contains("TALUS-001"));
        assert!(json.contains("365"));
    }

    #[test]
    fn feature_list_contains_all_enterprise_features() {
        let state = LicenseState::trial();
        let features = state.feature_list();
        let required = [
            "tui",
            "plain",
            "json",
            "web",
            "auto_kill",
            "kafka",
            "clickhouse",
            "memgraph",
            "ffi",
        ];
        for req in &required {
            assert!(
                features.contains(&req.to_string()),
                "trial should include {req}"
            );
        }
    }

    #[test]
    fn community_mode_blocks_enterprise_features() {
        let state = LicenseState::community();
        assert!(!state.allows("auto_kill"));
        assert!(!state.allows("web"));
        assert!(!state.allows("kafka"));
        assert!(!state.allows("clickhouse"));
        assert!(!state.allows("memgraph"));
        assert!(!state.allows("ffi"));
        // But basic features should work
        assert!(state.allows("tui"));
        assert!(state.allows("json"));
        assert!(state.allows("plain"));
    }
}
