// ── Talus License Server — Cloudflare Worker + D1 ─────────────────────────
//
// Implements the client contract from process-monitor/src/license.rs:
//
//   POST /api/v1/activate    { license_key, machine_id, hostname, version }
//                            → { success, token, expires_at, tier, message }
//   POST /api/v1/deactivate  { license_id, token } → releases the machine seat
//   GET  /api/v1/health      → service status
//
// Security properties:
//   • The server holds ONLY the Ed25519 public key — the signing private key
//     never leaves the owner's machine (~/.secrets/talus/license-keys/).
//   • Every license key's signature is verified server-side before any
//     activation is recorded.
//   • Seat control is authoritative: max_seats enforced in D1, same-machine
//     re-activation is idempotent.
//   • Revocation: a `revoked` flag on the license row, plus a `revocations`
//     table for keys revoked before they were ever seen ("first-seen"
//     auto-registration otherwise applies).
//   • Rate limiting: per machine_id AND global, 5 activation attempts per
//     5 minutes (fixed window in D1).
//   • No tokens or license keys are ever logged.
//   • Admin endpoints (rotate-approval / revoke) require the ADMIN_TOKEN
//     secret via `Authorization: Bearer <token>`.
//
// ── Admin panel (served by this worker at /admin) ─────────────────────────
//
//   GET  /admin                 → login page (or overview when a valid
//                                 session cookie is present)
//   POST /admin/login           { auth_code, totp } → sets HttpOnly cookie
//   POST /admin/logout          → clears the session
//   GET  /admin/session-check   → { success } when the cookie is valid
//
// Login = ADMIN_TOKEN (possession) + TOTP (Google Authenticator, RFC 6238,
// HMAC-SHA1 via WebCrypto). Successful login creates a 12h session in D1
// (sessions table stores only SHA-256 hashes of session tokens). Failed
// logins are rate-limited; used TOTP time-steps are recorded in `totp_used`
// and never accepted twice (replay protection).
//
// Secret (wrangler secret put): TOTP_SECRET — base32 seed, generated by
// scripts/setup-totp.sh, shown to the owner exactly once (as otpauth:// URL
// and QR code).

// Ed25519 verification uses the runtime's native WebCrypto (Ed25519 is
// supported by workerd), so there is no third-party crypto dependency.
//
// Admin panel assets are imported as text (text-bundling rule in
// wrangler.toml) — no build step, no CDN, nothing served from outside.
import login_html from './admin-assets/login.html';
import admin_html from './admin-assets/admin.html';
import admin_css from './admin-assets/style.css';
import admin_js from './admin-assets/app.js';

// ── Environment / secrets ─────────────────────────────────────────────────
//
// vars (wrangler.toml):
//   LICENSE_PUBLIC_KEY_HEX — Ed25519 public key, hex (matches the key
//                            embedded in the Talus binary)
// secrets (wrangler secret put):
//   ADMIN_TOKEN — bearer token for /api/v1/admin/*

function env_error(name) {
  return json_response(
    { success: false, message: `server misconfigured: missing ${name}` },
    500,
  );
}

// ── Constants ─────────────────────────────────────────────────────────────

const MAX_BODY_BYTES = 16 * 1024; // 16 KiB is far more than any valid request
const RATE_LIMIT = 5; // activation attempts
const RATE_WINDOW_S = 300; // per 5 minutes
const ISO_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/;

// ── Router ────────────────────────────────────────────────────────────────

export default {
  async fetch(request, env) {
    try {
      const url = new URL(request.url);
      const { pathname } = url;

      // Restrict methods per route family; everything else → 405.
      if (request.method !== 'GET' && request.method !== 'POST') {
        return json_response({ success: false, message: 'method not allowed' }, 405);
      }

      if (pathname === '/api/v1/health' && request.method === 'GET') {
        return handle_health(env);
      }

      if (pathname === '/api/v1/activate' && request.method === 'POST') {
        return handle_activate(request, env);
      }

      if (pathname === '/api/v1/deactivate' && request.method === 'POST') {
        return handle_deactivate(request, env);
      }

      if (pathname === '/api/v1/admin/stats' && request.method === 'GET') {
        return handle_admin_stats(request, env);
      }

      if (pathname.startsWith('/api/v1/admin/') && request.method === 'POST') {
        return handle_admin(request, env, pathname);
      }

      // ── Admin panel (web UI, TOTP session) ──────────────────────────────
      if (pathname === '/admin' || pathname === '/admin/') {
        return serve_admin_entry(request, env);
      }
      if (pathname === '/admin/login' && request.method === 'POST') {
        return handle_admin_login(request, env);
      }
      if (pathname === '/admin/logout' && request.method === 'POST') {
        return handle_admin_logout(request, env);
      }
      if (pathname === '/admin/session-check' && request.method === 'GET') {
        const authz = await require_admin(request, env);
        return session_response(authz.admin === true);
      }
      if (pathname.startsWith('/admin/') && request.method === 'GET') {
        return serve_admin_asset(env, pathname);
      }

      return json_response({ success: false, message: 'not found' }, 404);
    } catch (err) {
      // Never leak internals; never log tokens or keys.
      return json_response(
        { success: false, message: 'internal server error' },
        500,
      );
    }
  },
};

// ── Handlers ──────────────────────────────────────────────────────────────

async function handle_health(env) {
  if (!env.DB) return env_error('DB binding');
  const { results } = await env.DB.prepare(
    'SELECT COUNT(*) AS n FROM activations',
  ).all();
  return json_response({
    success: true,
    service: 'talus-license-server',
    version: 1,
    activations: results?.[0]?.n ?? 0,
    time: new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
  });
}

async function handle_activate(request, env) {
  if (!env.DB) return env_error('DB binding');
  if (!env.LICENSE_PUBLIC_KEY_HEX) return env_error('LICENSE_PUBLIC_KEY_HEX');

  const body = await read_json(request);
  if (!body.ok) {
    return json_response({ success: false, message: body.error }, 400);
  }

  const license_key = str_field(body.value.license_key);
  const machine_id = str_field(body.value.machine_id);
  const hostname = str_field(body.value.hostname);
  // `version` is informational — accepted but not persisted.

  if (!license_key || !machine_id) {
    return json_response(
      { success: false, message: 'missing license_key or machine_id' },
      400,
    );
  }
  if (machine_id.length > 64 || license_key.length > 8192) {
    return json_response({ success: false, message: 'field too long' }, 400);
  }

  // ── Rate limiting: per machine, then global ────────────────────────────
  const limited = await rate_limit(env.DB, machine_id);
  if (limited) {
    return json_response(
      { success: false, message: 'too many activation attempts — try again later' },
      429,
    );
  }

  // ── Signature verification (server holds the public key only) ──────────
  const parts = license_key.split('.');
  if (parts.length !== 2) {
    return json_response(
      { success: false, message: 'invalid license key format' },
      400,
    );
  }
  let payload_bytes;
  let sig_bytes;
  try {
    payload_bytes = base64_decode(parts[0]);
    sig_bytes = base64_decode(parts[1]);
  } catch {
    return json_response({ success: false, message: 'invalid base64 encoding' }, 400);
  }
  if (sig_bytes.length !== 64) {
    return json_response({ success: false, message: 'invalid signature length' }, 400);
  }
  let pub_bytes;
  try {
    pub_bytes = hex_decode(env.LICENSE_PUBLIC_KEY_HEX);
  } catch {
    return env_error('LICENSE_PUBLIC_KEY_HEX');
  }
  if (!(await verify_ed25519(pub_bytes, sig_bytes, payload_bytes))) {
    return json_response(
      { success: false, message: 'license signature verification failed' },
      401,
    );
  }

  let payload;
  try {
    payload = JSON.parse(new TextDecoder().decode(payload_bytes));
  } catch {
    return json_response({ success: false, message: 'invalid license payload' }, 400);
  }

  const license_id = str_field(payload.license_id);
  const tier = str_field(payload.tier);
  if (!license_id || !tier) {
    return json_response(
      { success: false, message: 'license payload missing fields' },
      400,
    );
  }

  // ── Expiry (from the signed payload) ───────────────────────────────────
  const expires_at = str_field(payload.expires_at);
  if (expires_at) {
    if (!ISO_RE.test(expires_at)) {
      return json_response(
        { success: false, message: 'license payload has invalid expiry' },
        400,
      );
    }
    if (new Date(expires_at).getTime() <= Date.now()) {
      return json_response(
        { success: false, message: `license ${license_id} has expired` },
        403,
      );
    }
  }

  // ── First-seen auto-registration + revocation checks ───────────────────
  // The keygen registry lives offline, so the server learns licenses on
  // first activation. A pre-registered row can only be created by an admin.
  const existing = await env.DB.prepare(
    'SELECT license_id, tier, max_seats, expires_at, revoked FROM licenses WHERE license_id = ?1',
  )
    .bind(license_id)
    .first();

  let max_seats;
  if (existing) {
    if (existing.revoked) {
      return json_response(
        { success: false, message: `license ${license_id} has been revoked` },
        403,
      );
    }
    if (existing.expires_at && ISO_RE.test(existing.expires_at)) {
      if (new Date(existing.expires_at).getTime() <= Date.now()) {
        return json_response(
          { success: false, message: `license ${license_id} has expired` },
          403,
        );
      }
    }
    max_seats = existing.max_seats ?? 1;
  } else {
    const pre_revoked = await env.DB.prepare(
      'SELECT license_id FROM revocations WHERE license_id = ?1',
    )
      .bind(license_id)
      .first();
    if (pre_revoked) {
      return json_response(
        { success: false, message: `license ${license_id} has been revoked` },
        403,
      );
    }
    // Register on first sight. seat_count comes from the SIGNED payload, so
    // clients cannot inflate it — only the key holder can set it.
    const seat_count = Number(payload.seat_count);
    max_seats =
      Number.isInteger(seat_count) && seat_count > 0 ? seat_count : 1;
    await env.DB.prepare(
      `INSERT INTO licenses (license_id, tier, org, features, max_nodes, max_seats, expires_at, revoked, issued_at)
       VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 0, ?8)`,
    )
      .bind(
        license_id,
        tier,
        str_field(payload.organization) ?? null,
        payload.features ? JSON.stringify(payload.features) : null,
        Number(payload.max_nodes) || 0,
        max_seats,
        expires_at ?? null,
        str_field(payload.issued_at) ?? new Date().toISOString(),
      )
      .run();
  }

  // ── Seat control ───────────────────────────────────────────────────────
  const prev = await env.DB.prepare(
    'SELECT token FROM activations WHERE license_id = ?1 AND machine_id = ?2',
  )
    .bind(license_id, machine_id)
    .first();

  if (prev) {
    // Idempotent re-activation: same machine gets its token back.
    return json_response({
      success: true,
      token: prev.token,
      expires_at: expires_at ?? null,
      tier,
      message: 'license already activated on this machine',
    });
  }

  const active = await env.DB.prepare(
    'SELECT COUNT(*) AS n FROM activations WHERE license_id = ?1',
  )
    .bind(license_id)
    .first();
  if ((active?.n ?? 0) >= max_seats) {
    return json_response(
      {
        success: false,
        message: `seat limit reached (${max_seats}) — deactivate another machine first`,
      },
      403,
    );
  }

  const token = new_token();
  const now = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  await env.DB.prepare(
    `INSERT INTO activations (license_id, machine_id, hostname, token, activated_at, seat_index, last_seen)
     VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?5)`,
  )
    .bind(license_id, machine_id, hostname || null, token, now, (active?.n ?? 0) + 1)
    .run();

  return json_response({
    success: true,
    token,
    expires_at: expires_at ?? null,
    tier,
    message: 'license activated',
  });
}

async function handle_deactivate(request, env) {
  if (!env.DB) return env_error('DB binding');

  const body = await read_json(request);
  if (!body.ok) {
    return json_response({ success: false, message: body.error }, 400);
  }

  const license_id = str_field(body.value.license_id);
  const token = str_field(body.value.token);
  if (!license_id || !token) {
    return json_response(
      { success: false, message: 'missing license_id or token' },
      400,
    );
  }

  // Token is required and matched exactly — cannot free someone else's seat.
  const row = await env.DB.prepare(
    'SELECT machine_id FROM activations WHERE license_id = ?1 AND token = ?2',
  )
    .bind(license_id, token)
    .first();

  if (!row) {
    // Same shape as a successful release → no seat enumeration oracle.
    return json_response({
      success: true,
      message: 'no matching activation — nothing to do',
    });
  }

  await env.DB.prepare(
    'DELETE FROM activations WHERE license_id = ?1 AND machine_id = ?2',
  )
    .bind(license_id, row.machine_id)
    .run();

  return json_response({
    success: true,
    message: 'license deactivated — seat released',
  });
}

async function handle_admin(request, env, pathname) {
  if (!env.DB) return env_error('DB binding');
  if (!env.ADMIN_TOKEN) return env_error('ADMIN_TOKEN');

  const authz = await require_admin(request, env);
  if (!authz.admin) {
    return json_response({ success: false, message: 'unauthorized' }, 401);
  }

  const action = pathname.slice('/api/v1/admin/'.length);
  const body = await read_json(request);
  if (!body.ok) {
    return json_response({ success: false, message: body.error }, 400);
  }
  const license_id = str_field(body.value.license_id);
  if (!license_id) {
    return json_response({ success: false, message: 'missing license_id' }, 400);
  }

  if (action === 'revoke') {
    const now = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
    const reason = str_field(body.value.reason) ?? null;

    // Cover both cases: seen licenses (flag) and never-seen keys (table).
    await env.DB.batch([
      env.DB.prepare('UPDATE licenses SET revoked = 1 WHERE license_id = ?1').bind(license_id),
      env.DB.prepare(
        'INSERT INTO revocations (license_id, reason, revoked_at) VALUES (?1, ?2, ?3) ON CONFLICT(license_id) DO UPDATE SET reason = ?2, revoked_at = ?3',
      ).bind(license_id, reason, now),
      // Revocation frees all seats — activations must not survive it.
      env.DB.prepare('DELETE FROM activations WHERE license_id = ?1').bind(license_id),
    ]);

    return json_response({ success: true, message: `license ${license_id} revoked` });
  }

  if (action === 'activations') {
    const { results } = await env.DB.prepare(
      'SELECT machine_id, hostname, seat_index, activated_at, last_seen FROM activations WHERE license_id = ?1 ORDER BY seat_index',
    )
      .bind(license_id)
      .all();
    return json_response({ success: true, activations: results ?? [] });
  }

  if (action === 'unrevoke') {
    // Reverse of revoke: clear the flag and the pre-activation entry.
    // Seats were already freed by the revocation — customers re-activate.
    await env.DB.batch([
      env.DB.prepare('UPDATE licenses SET revoked = 0 WHERE license_id = ?1').bind(license_id),
      env.DB.prepare('DELETE FROM revocations WHERE license_id = ?1').bind(license_id),
    ]);
    return json_response({ success: true, message: `license ${license_id} restored` });
  }

  if (action === 'register') {
    // Pre-register a license so it is visible in the panel from the moment
    // of issue (before the customer's first activation). The row must match
    // the signed payload — on any mismatch the signature wins (the row is
    // reset from the key at first activation).
    const tier = str_field(body.value.tier);
    if (!tier) {
      return json_response({ success: false, message: 'missing tier' }, 400);
    }
    const seat_count = Number(body.value.max_seats);
    const max_seats =
      Number.isInteger(seat_count) && seat_count > 0 ? seat_count : 1;
    const max_nodes = Number(body.value.max_nodes) || 0;
    const expires_at = str_field(body.value.expires_at);
    if (expires_at && !ISO_RE.test(expires_at)) {
      return json_response(
        { success: false, message: 'expires_at must be YYYY-MM-DDTHH:MM:SSZ' },
        400,
      );
    }
    const now = now_iso();
    await env.DB.prepare(
      `INSERT INTO licenses (license_id, tier, org, features, max_nodes, max_seats, expires_at, revoked, issued_at)
       VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 0, ?8)
       ON CONFLICT(license_id) DO UPDATE SET
         tier = excluded.tier,
         org = excluded.org,
         features = excluded.features,
         max_nodes = excluded.max_nodes,
         max_seats = excluded.max_seats,
         expires_at = excluded.expires_at`,
    )
      .bind(
        license_id,
        tier,
        str_field(body.value.org) ?? null,
        body.value.features ? JSON.stringify(body.value.features) : null,
        max_nodes,
        max_seats,
        expires_at ?? null,
        now,
      )
      .run();
    return json_response({
      success: true,
      message: `license ${license_id} pre-registered`,
    });
  }

  if (action === 'free-seat') {
    const machine_id = str_field(body.value.machine_id);
    if (!machine_id) {
      return json_response({ success: false, message: 'missing machine_id' }, 400);
    }
    const { meta } = await env.DB.prepare(
      'DELETE FROM activations WHERE license_id = ?1 AND machine_id = ?2',
    )
      .bind(license_id, machine_id)
      .run();
    const freed = meta?.changes ?? 0;
    return json_response({
      success: true,
      freed,
      message: freed > 0 ? `seat ${machine_id} freed` : 'no matching activation',
    });
  }

  return json_response({ success: false, message: 'unknown admin action' }, 404);
}

// ── Admin: overview stats ─────────────────────────────────────────────────
// Served under GET /api/v1/admin/stats (auth via the same bearer token).

async function handle_admin_stats(request, env) {
  if (!env.DB) return env_error('DB binding');
  if (!env.ADMIN_TOKEN) return env_error('ADMIN_TOKEN');

  const authz = await require_admin(request, env);
  if (!authz.admin) {
    return json_response({ success: false, message: 'unauthorized' }, 401);
  }

  const count = async (sql, ...binds) => {
    const row = await env.DB.prepare(sql)
      .bind(...binds)
      .first();
    return row?.n ?? 0;
  };

  const licenses = await count('SELECT COUNT(*) AS n FROM licenses');
  const revoked = await count('SELECT COUNT(*) AS n FROM licenses WHERE revoked = 1');
  const activations = await count('SELECT COUNT(*) AS n FROM activations');
  const week_ago = new Date(Date.now() - 7 * 86400_000).toISOString().replace(/\.\d{3}Z$/, 'Z');
  const activations_7d = await count(
    'SELECT COUNT(*) AS n FROM activations WHERE activated_at >= ?1',
    week_ago,
  );

  // Single-table queries merged in JS — avoids D1 join quirks.
  const { results: recent_rows } = await env.DB.prepare(
    'SELECT license_id, machine_id, hostname, activated_at FROM activations ORDER BY activated_at DESC LIMIT 10',
  ).all();

  const { results: license_rows } = await env.DB.prepare(
    'SELECT license_id, tier, org, expires_at, revoked FROM licenses',
  ).all();
  const license_map = new Map((license_rows ?? []).map((l) => [l.license_id, l]));

  const { results: revocation_rows } = await env.DB.prepare(
    'SELECT license_id, reason, revoked_at FROM revocations',
  ).all();
  const revocation_map = new Map((revocation_rows ?? []).map((r) => [r.license_id, r]));

  // Union of revoked sources: flagged licenses + pre-activation revocations.
  const revoked_ids = new Set([
    ...(license_rows ?? []).filter((l) => l.revoked).map((l) => l.license_id),
    ...(revocation_rows ?? []).map((r) => r.license_id),
  ]);
  const revoked_list = [...revoked_ids].map((id) => {
    const lic = license_map.get(id);
    const rev = revocation_map.get(id);
    return {
      license_id: id,
      org: lic?.org ?? null,
      revoked_at: rev?.revoked_at ?? null,
      reason: rev?.reason ?? null,
    };
  });

  const recent = (recent_rows ?? []).map((a) => {
    const l = license_map.get(a.license_id);
    return { ...a, tier: l?.tier ?? null, org: l?.org ?? null, revoked: l?.revoked ?? 0 };
  });

  return json_response({
    success: true,
    licenses,
    revoked,
    activations,
    activations_7d,
    recent,
    revoked_list,
    time: new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
  });
}

// ── Admin auth: ADMIN_TOKEN bearer OR TOTP-backed web session ────────────
//
// API admin endpoints accept either credential: the bearer token (CLI,
// scripts, local panel proxy) or the browser session cookie set by a
// TOTP login at /admin. Web-session handling lives entirely in the worker.

const ADMIN_COOKIE = 'talus_admin_session';
const SESSION_TTL_S = 12 * 3600; // 12 hours
const TOTP_STEP = 30; // RFC 6238 / Google Authenticator default
const TOTP_DIGITS = 6;
const TOTP_WINDOW = 1; // accept step-1 / current / step+1
const LOGIN_RATE = 10; // failed login attempts
const LOGIN_WINDOW_S = 300; // per 5 minutes

// Returns { admin: true } for valid credentials, { admin: false } otherwise.
// Never throws on missing credentials — callers decide the response shape.
async function require_admin(request, env) {
  // 1) Bearer token (existing flow).
  const auth = (request.headers.get('Authorization') ?? '').trim();
  const expected = `Bearer ${String(env.ADMIN_TOKEN ?? '').trim()}`;
  if (
    env.ADMIN_TOKEN &&
    auth.length > 0 &&
    auth.length === expected.length &&
    timing_safe_equal(auth, expected)
  ) {
    return { admin: true, via: 'bearer' };
  }

  // 2) Web session cookie (TOTP login at /admin).
  const cookie = request.headers.get('Cookie') ?? '';
  const match = cookie.match(
    new RegExp(`(?:^|;\\s*)${ADMIN_COOKIE}=([A-Za-z0-9_-]+)`),
  );
  if (match) {
    const valid = await session_valid(env, match[1]);
    if (valid) return { admin: true, via: 'session' };
  }
  return { admin: false };
}

// ── Sessions (D1, token stored as SHA-256 hash only) ──────────────────────

async function session_valid(env, token) {
  const hash = await sha256_hex(token);
  const row = await env.DB.prepare(
    'SELECT expires_at FROM sessions WHERE token_hash = ?1',
  )
    .bind(hash)
    .first();
  if (!row) return false;
  if (new Date(row.expires_at).getTime() <= Date.now()) {
    await env.DB.prepare('DELETE FROM sessions WHERE token_hash = ?1')
      .bind(hash)
      .run();
    return false;
  }
  // Rolling last_seen for a light audit trail.
  await env.DB.prepare('UPDATE sessions SET last_seen = ?1 WHERE token_hash = ?2')
    .bind(now_iso(), hash)
    .run();
  return true;
}

async function session_create(env) {
  const token = new_token();
  const now = Date.now();
  await env.DB.prepare(
    `INSERT INTO sessions (token_hash, created_at, last_seen, expires_at)
     VALUES (?1, ?2, ?2, ?3)`,
  )
    .bind(await sha256_hex(token), now_iso(now), now_iso(now + SESSION_TTL_S * 1000))
    .run();
  return token;
}

function session_cookie(token, max_age_s) {
  // HttpOnly + Secure + SameSite=Strict: the JS never touches the cookie,
  // it only talks to the API with credentials: 'include'.
  return `${ADMIN_COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${max_age_s}`;
}

async function handle_admin_login(request, env) {
  if (!env.DB) return env_error('DB binding');
  if (!env.ADMIN_TOKEN) return env_error('ADMIN_TOKEN');
  if (!env.TOTP_SECRET) return env_error('TOTP_SECRET');

  const body = await read_json(request);
  if (!body.ok) {
    return json_response({ success: false, message: body.error }, 400);
  }

  const auth_code = str_field(body.value.auth_code) ?? '';
  const totp = str_field(body.value.totp) ?? '';
  if (!auth_code || !totp) {
    return json_response(
      { success: false, message: 'missing auth_code or totp' },
      400,
    );
  }

  // Rate limit failed logins (per credential prefix, not machine-wide).
  if (await login_rate_limited(env, auth_code)) {
    return json_response(
      { success: false, message: 'too many failed attempts — try again later' },
      429,
    );
  }

  // Check the auth code FIRST: a failed overall login must not consume the
  // caller's TOTP step (otherwise a typo in the auth code would force the
  // owner to wait 30 s for the next code).
  // Accept both the raw token (what the login form asks for) and the
  // "Bearer <token>" form (CLI habit).
  const raw = String(env.ADMIN_TOKEN).trim();
  const auth_ok = [raw, `Bearer ${raw}`].some(
    (candidate) =>
      auth_code.length === candidate.length && timing_safe_equal(auth_code, candidate),
  );
  if (!auth_ok) {
    await record_login_failure(env, auth_code);
    return json_response({ success: false, message: 'invalid credentials' }, 401);
  }

  const totp_ok = await totp_verify(env, totp.trim());
  if (!totp_ok) {
    await record_login_failure(env, auth_code);
    return json_response({ success: false, message: 'invalid credentials' }, 401);
  }

  const token = await session_create(env);
  return json_response(
    { success: true, message: 'admin session established' },
    200,
    { 'set-cookie': session_cookie(token, SESSION_TTL_S) },
  );
}

async function handle_admin_logout(request, env) {
  const cookie = request.headers.get('Cookie') ?? '';
  const match = cookie.match(
    new RegExp(`(?:^|;\\s*)${ADMIN_COOKIE}=([A-Za-z0-9_-]+)`),
  );
  if (match) {
    await env.DB.prepare('DELETE FROM sessions WHERE token_hash = ?1')
      .bind(await sha256_hex(match[1]))
      .run();
  }
  return json_response(
    { success: true, message: 'logged out' },
    200,
    { 'set-cookie': session_cookie('', 0) },
  );
}

// ── TOTP (RFC 6238, HMAC-SHA1, 6 digits, 30 s step) ───────────────────────
//
// Verification is fail-closed: any missing secret or malformed code fails.
// A successful check records the time-step in `totp_used` — the same step
// can never authorize a second login (replay protection).

async function totp_verify(env, code) {
  const secret = String(env.TOTP_SECRET ?? '').trim();
  if (!secret) return false;
  if (!/^\d{6}$/.test(code)) return false;

  const key_bytes = base32_decode(secret.replace(/\s+/g, '').toUpperCase());
  if (!key_bytes) return false;

  const counter = Math.floor(Date.now() / 1000 / TOTP_STEP);
  const code_num = parseInt(code, 10);

  for (let drift = -TOTP_WINDOW; drift <= TOTP_WINDOW; drift++) {
    const step = counter + drift;
    if (step < 0) continue;
    const expected = await totp_at(key_bytes, step);
    if (expected === code_num) {
      // Replay guard: reject steps that were already consumed. The window is
      // ±1 step, so pruning anything older than the window keeps it tiny.
      const cutoff = counter - TOTP_WINDOW - 1;
      await env.DB.prepare('DELETE FROM totp_used WHERE counter < ?1')
        .bind(cutoff)
        .run();
      const used = await env.DB.prepare(
        'SELECT counter FROM totp_used WHERE counter = ?1',
      )
        .bind(step)
        .first();
      if (used) return false;
      await env.DB.prepare(
        'INSERT INTO totp_used (counter, used_at) VALUES (?1, ?2)',
      )
        .bind(step, now_iso())
        .run();
      return true;
    }
  }
  return false;
}

// HOTP core: HMAC-SHA1(key, counter_be64) → dynamic truncation → % 10^6.
async function totp_at(key_bytes, counter) {
  const key = await crypto.subtle.importKey(
    'raw',
    key_bytes,
    { name: 'HMAC', hash: 'SHA-1' },
    false,
    ['sign'],
  );
  const msg = new Uint8Array(8);
  new DataView(msg.buffer).setBigUint64(0, BigInt(counter));
  const mac = new Uint8Array(await crypto.subtle.sign('HMAC', key, msg));
  const off = mac[mac.length - 1] & 0x0f;
  const bin =
    ((mac[off] & 0x7f) << 24) |
    (mac[off + 1] << 16) |
    (mac[off + 2] << 8) |
    mac[off + 3];
  return bin % 10 ** TOTP_DIGITS;
}

// Standard RFC 4648 base32 (A–Z, 2–7), padding optional, no inline spaces.
function base32_decode(s) {
  if (!/^[A-Z2-7]+=*$/.test(s)) return null;
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let bits = 0;
  let value = 0;
  const out = [];
  for (const ch of s.replace(/=+$/, '')) {
    const idx = alphabet.indexOf(ch);
    if (idx < 0) return null;
    value = (value << 5) | idx;
    bits += 5;
    if (bits >= 8) {
      out.push((value >>> (bits - 8)) & 0xff);
      bits -= 8;
    }
  }
  return new Uint8Array(out);
}

function base32_encode(bytes) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let bits = 0;
  let value = 0;
  let out = '';
  for (const b of bytes) {
    value = (value << 8) | b;
    bits += 8;
    while (bits >= 5) {
      out += alphabet[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) out += alphabet[(value << (5 - bits)) & 31];
  return out;
}

// ── Admin panel static UI (/admin) ────────────────────────────────────────

async function serve_admin_entry(request, env) {
  const auth = await require_admin(request, env);
  if (!auth.admin || auth.via === 'bearer') {
    // No valid session → login page. (Bearer-authenticated requests get the
    // login page too: the browser UI is meant for the TOTP session flow.)
    return new Response(login_html, {
      headers: {
        'content-type': 'text/html; charset=utf-8',
        'cache-control': 'no-store',
        'x-content-type-options': 'nosniff',
        'referrer-policy': 'no-referrer',
      },
    });
  }
  // Valid session → overview UI.
  return new Response(admin_html, {
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'no-store',
      'x-content-type-options': 'nosniff',
      'referrer-policy': 'no-referrer',
    },
  });
}

async function serve_admin_asset(env, pathname) {
  if (pathname === '/admin/app.js') {
    return new Response(admin_js, {
      headers: {
        'content-type': 'text/javascript; charset=utf-8',
        'cache-control': 'no-store',
        'x-content-type-options': 'nosniff',
      },
    });
  }
  if (pathname === '/admin/style.css') {
    return new Response(admin_css, {
      headers: {
        'content-type': 'text/css; charset=utf-8',
        'cache-control': 'no-store',
        'x-content-type-options': 'nosniff',
      },
    });
  }
  return json_response({ success: false, message: 'not found' }, 404);
}

function session_response(valid) {
  return json_response(
    { success: valid },
    valid ? 200 : 401,
  );
}

// ── Login rate limiting (failed attempts only) ────────────────────────────

async function login_rate_limited(env, auth_code) {
  // Prune first, then check — same pattern as activation rate limiting.
  const now = Math.floor(Date.now() / 1000);
  await env.DB.prepare('DELETE FROM rate_events WHERE ts < ?1')
    .bind(now - LOGIN_WINDOW_S)
    .run();
  const bucket = `login:${auth_code.slice(0, 24)}`;
  const { results } = await env.DB.prepare(
    'SELECT COUNT(*) AS n FROM rate_events WHERE bucket = ?1 AND ts >= ?2',
  )
    .bind(bucket, now - LOGIN_WINDOW_S)
    .all();
  return (results?.[0]?.n ?? 0) >= LOGIN_RATE;
}

async function record_login_failure(env, auth_code) {
  const bucket = `login:${auth_code.slice(0, 24)}`;
  await env.DB.prepare(
    'INSERT INTO rate_events (bucket, ts) VALUES (?1, ?2)',
  )
    .bind(bucket, Math.floor(Date.now() / 1000))
    .run();
}

// ── Shared helpers ────────────────────────────────────────────────────────

async function sha256_hex(s) {
  const digest = await crypto.subtle.digest(
    'SHA-256',
    new TextEncoder().encode(s),
  );
  return [...new Uint8Array(digest)]
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

function now_iso(ms = Date.now()) {
  return new Date(ms).toISOString().replace(/\.\d{3}Z$/, 'Z');
}

// ── Rate limiting ─────────────────────────────────────────────────────────

async function rate_limit(db, machine_id) {
  const now = Math.floor(Date.now() / 1000);
  const window_start = now - RATE_WINDOW_S;
  const global_bucket = `global:${Math.floor(now / RATE_WINDOW_S)}`;
  const machine_bucket = `machine:${machine_id}:${Math.floor(now / RATE_WINDOW_S)}`;

  // Prune old events, then record this attempt.
  await db
    .prepare('DELETE FROM rate_events WHERE ts < ?1')
    .bind(window_start)
    .run();
  await db
    .prepare('INSERT INTO rate_events (bucket, ts) VALUES (?1, ?2)')
    .bind(machine_bucket, now)
    .run();

  const per_machine = await count_events(db, machine_bucket, window_start);
  if (per_machine > RATE_LIMIT) return true;

  const global = await count_events(db, global_bucket, window_start);
  // Global cap is intentionally loose (abuse brake, not a per-user limit).
  return global > RATE_LIMIT * 200;
}

async function count_events(db, bucket, window_start) {
  const { results } = await db
    .prepare('SELECT COUNT(*) AS n FROM rate_events WHERE bucket = ?1 AND ts >= ?2')
    .bind(bucket, window_start)
    .all();
  return results?.[0]?.n ?? 0;
}

// ── Helpers ───────────────────────────────────────────────────────────────

async function read_json(request) {
  const raw = await request.text();
  if (raw.length > MAX_BODY_BYTES) {
    return { ok: false, error: 'request body too large' };
  }
  try {
    const value = JSON.parse(raw);
    if (!value || typeof value !== 'object' || Array.isArray(value)) {
      return { ok: false, error: 'invalid JSON body' };
    }
    return { ok: true, value };
  } catch {
    return { ok: false, error: 'invalid JSON body' };
  }
}

function str_field(v) {
  return typeof v === 'string' && v.length > 0 ? v : null;
}

function base64_decode(s) {
  const norm = s.replace(/-/g, '+').replace(/_/g, '/');
  const bin = atob(norm);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function hex_decode(s) {
  if (!/^[0-9a-fA-F]+$/.test(s) || s.length % 2 !== 0) {
    throw new Error('bad hex');
  }
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

// Native WebCrypto Ed25519 verification (workerd supports Ed25519).
async function verify_ed25519(public_key, signature, data) {
  try {
    const key = await crypto.subtle.importKey(
      'raw',
      public_key,
      { name: 'Ed25519' },
      false,
      ['verify'],
    );
    return await crypto.subtle.verify(
      { name: 'Ed25519' },
      key,
      signature,
      data,
    );
  } catch {
    return false;
  }
}

function new_token() {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  let bin = '';
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function timing_safe_equal(a, b) {
  let diff = a.length ^ b.length;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function json_response(obj, status = 200, extra_headers = null) {
  const headers = {
    'content-type': 'application/json',
    'cache-control': 'no-store',
    'x-content-type-options': 'nosniff',
    'allow': 'GET, POST',
    ...(extra_headers ?? {}),
  };
  return new Response(JSON.stringify(obj), { status, headers });
}
